util.PrecacheSound( "vox/deeoo.wav" )
if SERVER then
    PrintMessage(HUD_PRINTTALK, "SERVER IS RELOADING THE GAMEMODE DUE TO AN EDIT IN THE GAMEMODE'S CODE - GRAPHICAL OR GAME-BREAKING GLITCHES MAY OCCUR")
    PrintMessage(HUD_PRINTCENTER, "SERVER IS RELOADING THE GAMEMODE DUE TO AN EDIT IN THE GAMEMODE'S CODE - GRAPHICAL OR GAME-BREAKING GLITCHES MAY OCCUR")
end
print("Including TF2 Particles")
AddCSLuaFile() 
game.AddParticles("particles/bigboom.pcf")
game.AddParticles("particles/blood_impact.pcf")
game.AddParticles("particles/blood_trail.pcf")
game.AddParticles("particles/bl_killtaunt.pcf")
game.AddParticles("particles/bombinomicon.pcf")
game.AddParticles("particles/buildingdamage.pcf")
game.AddParticles("particles/buildingdamage.pcf")
game.AddParticles("particles/bullet_tracers.pcf")
game.AddParticles("particles/burningplayer.pcf")
game.AddParticles("particles/cig_smoke.pcf")
game.AddParticles("particles/cinefx.pcf")
game.AddParticles("particles/class_fx.pcf")
game.AddParticles("particles/coin_spin.pcf")
game.AddParticles("particles/conc_stars.pcf")
game.AddParticles("particles/crit.pcf")
game.AddParticles("particles/dirty_explode.pcf")
game.AddParticles("particles/disguise.pcf")
game.AddParticles("particles/doomsday_fx.pcf")
game.AddParticles("particles/drg_bison.pcf")
game.AddParticles("particles/drg_cowmangler.pcf")
game.AddParticles("particles/drg_engineer.pcf")
game.AddParticles("particles/drg_pyro.pcf")
game.AddParticles("particles/dxhr_fx.pcf")
game.AddParticles("particles/explosion.pcf")
game.AddParticles("particles/eyeboss.pcf")
game.AddParticles("particles/flag_particles.pcf")
game.AddParticles("particles/flamethrower.pcf")
game.AddParticles("particles/flamethrower_mvm.pcf")
game.AddParticles("particles/halloween.pcf")
game.AddParticles("particles/harbor_fx.pcf")
game.AddParticles("particles/highfive.pcf")
game.AddParticles("particles/impact_fx.pcf")
game.AddParticles("particles/items_demo.pcf")
game.AddParticles("particles/items_engineer.pcf")
game.AddParticles("particles/item_fx.pcf")
game.AddParticles("particles/level_fx.pcf")
game.AddParticles("particles/medicgun_attrib.pcf")
game.AddParticles("particles/medicgun_beam.pcf")
game.AddParticles("particles/muzzle_flash.pcf")
game.AddParticles("particles/mvm.pcf")
game.AddParticles("particles/nailtrails.pcf")
game.AddParticles("particles/nemesis.pcf")
game.AddParticles("particles/npc_fx.pcf")
game.AddParticles("particles/player_recent_teleport.pcf")
game.AddParticles("particles/rain_custom.pcf")
game.AddParticles("particles/rocketbackblast.pcf")
game.AddParticles("particles/rocketjumptrail.pcf")
game.AddParticles("particles/rockettrail.pcf")
game.AddParticles("particles/scary_ghost.pcf")
game.AddParticles("particles/shellejection.pcf")
game.AddParticles("particles/smoke_blackbillow.pcf")
game.AddParticles("particles/smoke_blackbillow_hoodoo.pcf")
game.AddParticles("particles/soldierbuff.pcf")
game.AddParticles("particles/sparks.pcf")
game.AddParticles("particles/speechbubbles.pcf")
game.AddParticles("particles/stamp_spin.pcf")
game.AddParticles("particles/stickybomb.pcf")
game.AddParticles("particles/stormfront.pcf")
game.AddParticles("particles/teleported_fx.pcf")
game.AddParticles("particles/teleport_status.pcf")
game.AddParticles("particles/training.pcf")
game.AddParticles("particles/water.pcf")
game.AddParticles("particles/xms.pcf")

if (IsMounted("left4dead2")) then

    game.AddParticles( "particles/l4d2/blood_impact.pcf" )
    game.AddParticles( "particles/l4d2/impact_fx.pcf" )
    game.AddParticles( "particles/l4d2/boomer_fx.pcf" )
    game.AddParticles( "particles/l4d2/burning_fx.pcf" )
    game.AddParticles( "particles/l4d2/charger_fx.pcf" )
    game.AddParticles( "particles/l4d2/coldstream.pcf" )
    game.AddParticles( "particles/l4d2/electrical_fx.pcf" )
    game.AddParticles( "particles/l4d2/fire_01_lighthouse.pcf" )
    game.AddParticles( "particles/l4d2/fire_01_river.pcf" )
    game.AddParticles( "particles/l4d2/fire_01l4d.pcf" )
    game.AddParticles( "particles/l4d2/fire_01.pcf" )
    game.AddParticles( "particles/l4d2/fire_01l4d_garage.pcf" )
    game.AddParticles( "particles/l4d2/fire_01l4d_river.pcf" )
    game.AddParticles( "particles/l4d2/fire_fx.pcf" )
    game.AddParticles( "particles/l4d2/fire_infected_fx.pcf" )
    game.AddParticles( "particles/l4d2/firework_crate_fx.pcf" )
    game.AddParticles( "particles/l4d2/fireworks_fx.pcf" )
    game.AddParticles( "particles/l4d2/footstep_fx.pcf" )
    game.AddParticles( "particles/l4d2/gen_dest_fx.pcf" )
    game.AddParticles( "particles/l4d2/hunter_fx.pcf" )
    game.AddParticles( "particles/l4d2/infected_fx.pcf" )
    game.AddParticles( "particles/l4d2/insect_fx.pcf" )
    game.AddParticles( "particles/l4d2/item_fx.pcf" )
    game.AddParticles( "particles/l4d2/laststand.pcf" )
    game.AddParticles( "particles/l4d2/military_artillery_impacts.pcf" )
    game.AddParticles( "particles/l4d2/smoker_fx.pcf" )
    game.AddParticles( "particles/l4d2/spitter_fx.pcf" )
    game.AddParticles( "particles/l4d2/steam_fx.pcf" )
    game.AddParticles( "particles/l4d2/survivor_fx.pcf" )
    game.AddParticles( "particles/l4d2/tank_fx.pcf" )
    game.AddParticles( "particles/l4d2/tanker_explosion.pcf" )
    game.AddParticles( "particles/l4d2/vehicle_fx.pcf" )
    game.AddParticles( "particles/l4d2/weapon_fx.pcf" )
    game.AddParticles( "particles/l4d2/weapon_fx_newbrasseject.pcf" )
    game.AddParticles( "particles/l4d2/weapon_fx_river.pcf" )
    game.AddParticles( "particles/l4d2/witch_fx.pcf" )
    game.AddParticles( "particles/l4d2/vehicle_fx.pcf" )
    game.AddParticles( "particles/l4d2/laststand.pcf" )

    
end